<template>
  <div>
    <NavbarDefault />

    <div><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tbody><tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tbody><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>
              <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a href="ask">ask</a> | <a href="show">show</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              <a href="login?goto=news">login</a>
                          </span></td>
      </tr></tbody></table></td></tr>
      <tr id="pagespace" title="" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
        <tbody><tr class="athing" id="25273907">
          <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25273907" href="vote?id=25273907&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://c9x.me/compile/doc/llvm.html" class="storylink">QBE vs. LLVM</a><span class="sitebit comhead"> (<a href="from?site=c9x.me"><span class="sitestr">c9x.me</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25273907">131 points</span> by <a href="user?id=peter_d_sherman" class="hnuser">peter_d_sherman</a> <span class="age"><a href="item?id=25273907">4 hours ago</a></span> <span id="unv_25273907"></span> | <a href="hide?id=25273907&amp;goto=news">hide</a> | <a href="item?id=25273907">36&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25271791">
          <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25271791" href="vote?id=25271791&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://aws.amazon.com/s3/consistency/" class="storylink">S3 Strong Consistency</a><span class="sitebit comhead"> (<a href="from?site=amazon.com"><span class="sitestr">amazon.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25271791">531 points</span> by <a href="user?id=juliansimioni" class="hnuser">juliansimioni</a> <span class="age"><a href="item?id=25271791">11 hours ago</a></span> <span id="unv_25271791"></span> | <a href="hide?id=25271791&amp;goto=news">hide</a> | <a href="item?id=25271791">160&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25273895">
          <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25273895" href="vote?id=25273895&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.skywatertechnology.com/" class="storylink">Google partners with SkyWater to enable open source manufacturing of ASICs</a><span class="sitebit comhead"> (<a href="from?site=skywatertechnology.com"><span class="sitestr">skywatertechnology.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25273895">71 points</span> by <a href="user?id=lawrenceyan" class="hnuser">lawrenceyan</a> <span class="age"><a href="item?id=25273895">4 hours ago</a></span> <span id="unv_25273895"></span> | <a href="hide?id=25273895&amp;goto=news">hide</a> | <a href="item?id=25273895">23&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25274928">
          <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25274928" href="vote?id=25274928&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://a13xp0p0v.github.io/2020/11/30/slab-quarantine.html" class="storylink">Linux kernel heap quarantine versus use-after-free exploits</a><span class="sitebit comhead"> (<a href="from?site=a13xp0p0v.github.io"><span class="sitestr">a13xp0p0v.github.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25274928">18 points</span> by <a href="user?id=kmwyard" class="hnuser">kmwyard</a> <span class="age"><a href="item?id=25274928">1 hour ago</a></span> <span id="unv_25274928"></span> | <a href="hide?id=25274928&amp;goto=news">hide</a> | <a href="item?id=25274928">4&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25270184">
          <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25270184" href="vote?id=25270184&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://googleprojectzero.blogspot.com/2020/12/an-ios-zero-click-radio-proximity.html" class="storylink">An iOS zero-click radio proximity exploit odyssey</a><span class="sitebit comhead"> (<a href="from?site=googleprojectzero.blogspot.com"><span class="sitestr">googleprojectzero.blogspot.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25270184">519 points</span> by <a href="user?id=tbodt" class="hnuser">tbodt</a> <span class="age"><a href="item?id=25270184">13 hours ago</a></span> <span id="unv_25270184"></span> | <a href="hide?id=25270184&amp;goto=news">hide</a> | <a href="item?id=25270184">195&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25253498">
          <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25253498" href="vote?id=25253498&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://math.stackexchange.com/questions/30046/alternative-notation-for-exponents-logs-and-roots" class="storylink">Alternative notation for exponents, logs and roots</a><span class="sitebit comhead"> (<a href="from?site=stackexchange.com"><span class="sitestr">stackexchange.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25253498">39 points</span> by <a href="user?id=aleyan" class="hnuser">aleyan</a> <span class="age"><a href="item?id=25253498">2 hours ago</a></span> <span id="unv_25253498"></span> | <a href="hide?id=25253498&amp;goto=news">hide</a> | <a href="item?id=25253498">9&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25274123">
          <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25274123" href="vote?id=25274123&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://developers.facebook.com/docs/messenger-platform/europe-updates" class="storylink">Messenger API Updates for Europe</a><span class="sitebit comhead"> (<a href="from?site=facebook.com"><span class="sitestr">facebook.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25274123">32 points</span> by <a href="user?id=zsiciarz" class="hnuser">zsiciarz</a> <span class="age"><a href="item?id=25274123">3 hours ago</a></span> <span id="unv_25274123"></span> | <a href="hide?id=25274123&amp;goto=news">hide</a> | <a href="item?id=25274123">18&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25274699">
          <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25274699" href="vote?id=25274699&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://serhack.me/articles/hackers-full-control-of-online-compilers-through-a-common-exploit/" class="storylink">Hackers can take full control of online compilers through a RCE exploit (2018)</a><span class="sitebit comhead"> (<a href="from?site=serhack.me"><span class="sitestr">serhack.me</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25274699">9 points</span> by <a href="user?id=crecker" class="hnuser">crecker</a> <span class="age"><a href="item?id=25274699">2 hours ago</a></span> <span id="unv_25274699"></span> | <a href="hide?id=25274699&amp;goto=news">hide</a> | <a href="item?id=25274699">6&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25270001">
          <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25270001" href="vote?id=25270001&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://github.com/monicahq/monica" class="storylink">Monica: Personal CRM. Remember everything about your friends, family and etc.</a><span class="sitebit comhead"> (<a href="from?site=github.com/monicahq"><span class="sitestr">github.com/monicahq</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25270001">258 points</span> by <a href="user?id=tylermauthe" class="hnuser">tylermauthe</a> <span class="age"><a href="item?id=25270001">14 hours ago</a></span> <span id="unv_25270001"></span> | <a href="hide?id=25270001&amp;goto=news">hide</a> | <a href="item?id=25270001">126&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25271464">
          <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25271464" href="vote?id=25271464&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://archive.org/details/attentionkmartshoppers" class="storylink">Attention K-Mart Shoppers: Piped Music Collection on the Internet Archive</a><span class="sitebit comhead"> (<a href="from?site=archive.org"><span class="sitestr">archive.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25271464">218 points</span> by <a href="user?id=shervinafshar" class="hnuser">shervinafshar</a> <span class="age"><a href="item?id=25271464">11 hours ago</a></span> <span id="unv_25271464"></span> | <a href="hide?id=25271464&amp;goto=news">hide</a> | <a href="item?id=25271464">69&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25261591">
          <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25261591" href="vote?id=25261591&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://rootsofprogress.org/alphafold-protein-folding-explainer" class="storylink">What is protein folding? A brief explanation</a><span class="sitebit comhead"> (<a href="from?site=rootsofprogress.org"><span class="sitestr">rootsofprogress.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25261591">229 points</span> by <a href="user?id=jasoncrawford" class="hnuser">jasoncrawford</a> <span class="age"><a href="item?id=25261591">13 hours ago</a></span> <span id="unv_25261591"></span> | <a href="hide?id=25261591&amp;goto=news">hide</a> | <a href="item?id=25261591">64&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25264548">
          <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25264548" href="vote?id=25264548&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.esquire.com/news-politics/a34785141/shopping-mall-short-hedge-fund-covid-19/" class="storylink">The $2B Mall Rats</a><span class="sitebit comhead"> (<a href="from?site=esquire.com"><span class="sitestr">esquire.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25264548">46 points</span> by <a href="user?id=CapitalistCartr" class="hnuser">CapitalistCartr</a> <span class="age"><a href="item?id=25264548">6 hours ago</a></span> <span id="unv_25264548"></span> | <a href="hide?id=25264548&amp;goto=news">hide</a> | <a href="item?id=25264548">35&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25272957">
          <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25272957" href="vote?id=25272957&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://chess.resistant.tech/" class="storylink">Win by Segfault and Other Notes on Exploiting Chess Engines</a><span class="sitebit comhead"> (<a href="from?site=resistant.tech"><span class="sitestr">resistant.tech</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25272957">66 points</span> by <a href="user?id=wglb" class="hnuser">wglb</a> <span class="age"><a href="item?id=25272957">7 hours ago</a></span> <span id="unv_25272957"></span> | <a href="hide?id=25272957&amp;goto=news">hide</a> | <a href="item?id=25272957">3&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25269934">
          <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25269934" href="vote?id=25269934&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.salesforce.com/news/press-releases/2020/12/01/salesforce-definitive-agreement-update/" class="storylink">Salesforce Signs Definitive Agreement to Acquire Slack</a><span class="sitebit comhead"> (<a href="from?site=salesforce.com"><span class="sitestr">salesforce.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25269934">799 points</span> by <a href="user?id=jmsflknr" class="hnuser">jmsflknr</a> <span class="age"><a href="item?id=25269934">14 hours ago</a></span> <span id="unv_25269934"></span> | <a href="hide?id=25269934&amp;goto=news">hide</a> | <a href="item?id=25269934">578&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25273897">
          <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td></td><td class="title"><a href="https://mux.com/jobs" class="storylink" rel="nofollow">Mux (YC W16) is hiring a support engineer in ~UTC+0</a><span class="sitebit comhead"> (<a href="from?site=mux.com"><span class="sitestr">mux.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="age"><a href="item?id=25273897">4 hours ago</a></span> | <a href="hide?id=25273897&amp;goto=news">hide</a>      </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25264374">
          <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25264374" href="vote?id=25264374&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://arstechnica.com/science/2020/11/mars-underground-brine-could-be-a-good-source-of-oxygen/" class="storylink" rel="nofollow">Mars’ underground brine could be a good source of oxygen</a><span class="sitebit comhead"> (<a href="from?site=arstechnica.com"><span class="sitestr">arstechnica.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25264374">8 points</span> by <a href="user?id=rbanffy" class="hnuser">rbanffy</a> <span class="age"><a href="item?id=25264374">2 hours ago</a></span> <span id="unv_25264374"></span> | <a href="hide?id=25264374&amp;goto=news">hide</a> | <a href="item?id=25264374">1&nbsp;comment</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25273618">
          <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25273618" href="vote?id=25273618&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://thinkpol.ca/2020/12/01/airbnb-asked-canada-for-a-bailout-canada-slapped-airbnb-with-a-tax/" class="storylink">Canada to apply GST/HST to short-term rentals booked online</a><span class="sitebit comhead"> (<a href="from?site=thinkpol.ca"><span class="sitestr">thinkpol.ca</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25273618">54 points</span> by <a href="user?id=63labs" class="hnuser">63labs</a> <span class="age"><a href="item?id=25273618">5 hours ago</a></span> <span id="unv_25273618"></span> | <a href="hide?id=25273618&amp;goto=news">hide</a> | <a href="item?id=25273618">59&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25272726">
          <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25272726" href="vote?id=25272726&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://observablehq.com/@makio135/creative-coding" class="storylink">Observable and Creative Coding</a><span class="sitebit comhead"> (<a href="from?site=observablehq.com"><span class="sitestr">observablehq.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25272726">66 points</span> by <a href="user?id=grzm" class="hnuser">grzm</a> <span class="age"><a href="item?id=25272726">8 hours ago</a></span> <span id="unv_25272726"></span> | <a href="hide?id=25272726&amp;goto=news">hide</a> | <a href="item?id=25272726">5&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25272360">
          <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25272360" href="vote?id=25272360&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://alexlenail.me/NN-SVG/AlexNet.html" class="storylink">NN-SVG: Generate publication-ready NN-architecture schematics</a><span class="sitebit comhead"> (<a href="from?site=alexlenail.me"><span class="sitestr">alexlenail.me</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25272360">52 points</span> by <a href="user?id=tzm" class="hnuser">tzm</a> <span class="age"><a href="item?id=25272360">9 hours ago</a></span> <span id="unv_25272360"></span> | <a href="hide?id=25272360&amp;goto=news">hide</a> | <a href="item?id=25272360">6&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25253488">
          <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25253488" href="vote?id=25253488&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://deepmind.com/blog/article/alphafold-a-solution-to-a-50-year-old-grand-challenge-in-biology" class="storylink">AlphaFold: a solution to a 50-year-old grand challenge in biology</a><span class="sitebit comhead"> (<a href="from?site=deepmind.com"><span class="sitestr">deepmind.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25253488">1315 points</span> by <a href="user?id=momeara" class="hnuser">momeara</a> <span class="age"><a href="item?id=25253488">1 day ago</a></span> <span id="unv_25253488"></span> | <a href="hide?id=25253488&amp;goto=news">hide</a> | <a href="item?id=25253488">645&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25264555">
          <td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25264555" href="vote?id=25264555&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://www.space.com/arecibo-radio-telescope-collapses" class="storylink">Arecibo Observatory Collapsed</a><span class="sitebit comhead"> (<a href="from?site=space.com"><span class="sitestr">space.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25264555">628 points</span> by <a href="user?id=BrentOzar" class="hnuser">BrentOzar</a> <span class="age"><a href="item?id=25264555">22 hours ago</a></span> <span id="unv_25264555"></span> | <a href="hide?id=25264555&amp;goto=news">hide</a> | <a href="item?id=25264555">276&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25263488">
          <td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25263488" href="vote?id=25263488&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="http://number-none.com/blow/john_carmack_on_inlined_code.html" class="storylink">John Carmack on Inlined Code (2014)</a><span class="sitebit comhead"> (<a href="from?site=number-none.com"><span class="sitestr">number-none.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25263488">93 points</span> by <a href="user?id=tosh" class="hnuser">tosh</a> <span class="age"><a href="item?id=25263488">4 hours ago</a></span> <span id="unv_25263488"></span> | <a href="hide?id=25263488&amp;goto=news">hide</a> | <a href="item?id=25263488">89&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25274167">
          <td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25274167" href="vote?id=25274167&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://amycastor.com/2020/12/02/man-linked-to-missing-bitfinex-tether-funds-owes-lawyers-600000/" class="storylink" rel="nofollow">Reggie Fowler owes lawyers $600k</a><span class="sitebit comhead"> (<a href="from?site=amycastor.com"><span class="sitestr">amycastor.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25274167">10 points</span> by <a href="user?id=amycastor" class="hnuser">amycastor</a> <span class="age"><a href="item?id=25274167">3 hours ago</a></span> <span id="unv_25274167"></span> | <a href="hide?id=25274167&amp;goto=news">hide</a> | <a href="item?id=25274167">6&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25255718">
          <td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25255718" href="vote?id=25255718&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://blog.peterzhu.ca/ruby-inplace-bug/" class="storylink">Hunting Down the Ruby 'Inplace' Bug</a><span class="sitebit comhead"> (<a href="from?site=peterzhu.ca"><span class="sitestr">peterzhu.ca</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25255718">22 points</span> by <a href="user?id=petercooper" class="hnuser">petercooper</a> <span class="age"><a href="item?id=25255718">5 hours ago</a></span> <span id="unv_25255718"></span> | <a href="hide?id=25255718&amp;goto=news">hide</a> | <a href="item?id=25255718">3&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25267029">
          <td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25267029" href="vote?id=25267029&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://aws.amazon.com/lambda/pricing/" class="storylink">AWS Lambda pricing now per ms</a><span class="sitebit comhead"> (<a href="from?site=amazon.com"><span class="sitestr">amazon.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25267029">587 points</span> by <a href="user?id=astuyvenberg" class="hnuser">astuyvenberg</a> <span class="age"><a href="item?id=25267029">18 hours ago</a></span> <span id="unv_25267029"></span> | <a href="hide?id=25267029&amp;goto=news">hide</a> | <a href="item?id=25267029">265&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25272533">
          <td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25272533" href="vote?id=25272533&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://sacra.com/research/front-inside-the-startup-slackifying-email/?" class="storylink">Front: The $1.3B Startup Slackifying Email</a><span class="sitebit comhead"> (<a href="from?site=sacra.com"><span class="sitestr">sacra.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25272533">126 points</span> by <a href="user?id=bdr" class="hnuser">bdr</a> <span class="age"><a href="item?id=25272533">9 hours ago</a></span> <span id="unv_25272533"></span> | <a href="hide?id=25272533&amp;goto=news">hide</a> | <a href="item?id=25272533">112&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25265238">
          <td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25265238" href="vote?id=25265238&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="http://blog.erlang.org/the-road-to-the-jit/" class="storylink">The Road to the JIT</a><span class="sitebit comhead"> (<a href="from?site=erlang.org"><span class="sitestr">erlang.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25265238">216 points</span> by <a href="user?id=lelf" class="hnuser">lelf</a> <span class="age"><a href="item?id=25265238">20 hours ago</a></span> <span id="unv_25265238"></span> | <a href="hide?id=25265238&amp;goto=news">hide</a> | <a href="item?id=25265238">46&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25270107">
          <td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25270107" href="vote?id=25270107&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://brandur.org/large-database-casualties" class="storylink">Feature Casualties of Large Databases</a><span class="sitebit comhead"> (<a href="from?site=brandur.org"><span class="sitestr">brandur.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25270107">103 points</span> by <a href="user?id=craigkerstiens" class="hnuser">craigkerstiens</a> <span class="age"><a href="item?id=25270107">13 hours ago</a></span> <span id="unv_25270107"></span> | <a href="hide?id=25270107&amp;goto=news">hide</a> | <a href="item?id=25270107">31&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25273427">
          <td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25273427" href="vote?id=25273427&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="https://dev.to/bellmar/writing-a-bnf-grammar-featuring-prof-jeff-heinz-1cf0" class="storylink">Writing a BNF Grammar</a><span class="sitebit comhead"> (<a href="from?site=dev.to"><span class="sitestr">dev.to</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25273427">21 points</span> by <a href="user?id=mbellotti" class="hnuser">mbellotti</a> <span class="age"><a href="item?id=25273427">6 hours ago</a></span> <span id="unv_25273427"></span> | <a href="hide?id=25273427&amp;goto=news">hide</a> | <a href="item?id=25273427">2&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="athing" id="25271676">
          <td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id="up_25271676" href="vote?id=25271676&amp;how=up&amp;goto=news"><div class="votearrow" title="upvote"></div></a></center></td><td class="title"><a href="item?id=25271676" class="storylink">Ask HN: What are the best advanced computer science courses online?</a></td></tr><tr><td colspan="2"></td><td class="subtext">
          <span class="score" id="score_25271676">249 points</span> by <a href="user?id=st1x7" class="hnuser">st1x7</a> <span class="age"><a href="item?id=25271676">11 hours ago</a></span> <span id="unv_25271676"></span> | <a href="hide?id=25271676&amp;goto=news">hide</a> | <a href="item?id=25271676">66&nbsp;comments</a>              </td></tr>
        <tr class="spacer" style="height:5px"></tr>
        <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="news?p=2" class="morelink" rel="next">More</a></td></tr>
        </tbody></table>
      </td></tr>
      <tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tbody><tr><td bgcolor="#ff6600"></td></tr></tbody></table><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
        <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
      </center></td></tr>
      </tbody></table></center></div>
  </div>
</template>

<script>
import NavbarDefault from "../../../components/core/navbars/NavbarDefault";

export default {
  name: "News",
  components: {
    NavbarDefault
  },
}
</script>

<style scoped>
  /*@import "../../../../../resources/css/bootstrap.min.css";*/
  @import "../../../../../resources/css/styles.min.css";
</style>

